-- Create categories table
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create category translations table
CREATE TABLE category_translations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
  language_code TEXT NOT NULL, -- 'en', 'zh'
  name TEXT NOT NULL,
  UNIQUE(category_id, language_code)
);

-- Create products table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  key TEXT UNIQUE NOT NULL,
  image_url TEXT NOT NULL,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create product translations table
CREATE TABLE product_translations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  language_code TEXT NOT NULL, -- 'en', 'zh'
  name TEXT NOT NULL,
  description TEXT,
  specs JSONB DEFAULT '{}'::jsonb, -- Store specs as JSON: { material: "...", dimensions: "..." }
  UNIQUE(product_id, language_code)
);

-- Create contacts table
CREATE TABLE contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  status TEXT DEFAULT 'pending' -- 'pending', 'contacted', 'resolved'
);

-- Enable Row Level Security (RLS)
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE category_translations ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_translations ENABLE ROW LEVEL SECURITY;
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

-- Create policies (Adjust based on your needs)
-- Public read access
CREATE POLICY "Public categories are viewable by everyone" ON categories FOR SELECT USING (true);
CREATE POLICY "Public category_translations are viewable by everyone" ON category_translations FOR SELECT USING (true);
CREATE POLICY "Public products are viewable by everyone" ON products FOR SELECT USING (true);
CREATE POLICY "Public product_translations are viewable by everyone" ON product_translations FOR SELECT USING (true);

-- Admin full access (Assuming authenticated users are admins for now, or check specific role)
-- For simplicity, we allow authenticated users (admins) to do everything.
-- Ideally, you should check for a specific email or role.
CREATE POLICY "Admins can do everything on categories" ON categories FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins can do everything on category_translations" ON category_translations FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins can do everything on products" ON products FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins can do everything on product_translations" ON product_translations FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins can view contacts" ON contacts FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins can update contacts" ON contacts FOR UPDATE TO authenticated USING (true);

-- Allow public to insert contacts
CREATE POLICY "Public can insert contacts" ON contacts FOR INSERT WITH CHECK (true);
